version: '3.9'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: python app.py
        restart: always
        volumes:
            - .:/usr/projects/filterbot/src
        ports:
            - 8000:8000
        env_file:
            - ./config.ini
        depends_on:
            - db
    db:
        image: postgres:13.3
        volumes:
            - ./postgres_data:/var/lib/postgresql/data/
        restart: always
        env_file:
            - ./config.ini
        ports:
            - 5431:5432

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080